### ISSUE TITLE
Can advise the requirements.txt error?

### ISSUE THREAD

**Issue by winnerineast** [deep-diver/paper-reviewer#1]
I'm using conda to create virtual environment (python=3.11) and run "pip install -r requirements.txt".

I started to hit dependency issues continously.

first, "The conflict is caused by:
    The user requested pydantic==1.6.2
    fastapi 0.115.3 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4" and I changed pydantic to >=1.7.4,<3.0.0 and re-run "pip install -r requirements.txt".

then I hit "The conflict is caused by:
    The user requested typing-extensions==3.10.0.2
    fastapi 0.115.3 depends on typing-extensions>=4.8.0" and I changed "typing-extensions>=4.8.0" and re-run  "pip install -r requirements.txt".

then I hit "The conflict is caused by:
    The user requested httpx==0.14.3
    gradio 5.3.0 depends on httpx>=0.24.1"...

I follow the instruction to revise requirements.txt and try again and again but it always pops up new error. So I would like to have your advice how to install dependencies successfully. Thanks.

**Comment by deep-diver** [comment]
Hey @winnerineast 
Just noticed there are some conflictions.
Working on this problem, will ping you later today when it's fixed!

**Comment by deep-diver** [comment]
I think this should be resolved by now @winnerineast
